# Generated by Django 5.2.4 on 2025-09-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
