# Generated by Django 5.2.4 on 2025-09-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_mealplan_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='eaten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='eaten_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
