# Generated by Django 5.2.4 on 2025-09-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_mealplan_eaten_mealplan_eaten_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='date_created',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='spoonacular_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='carbs',
            field=models.CharField(default='0g', max_length=10),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='fats',
            field=models.CharField(default='0g', max_length=10),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='meal_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='protein',
            field=models.CharField(default='0g', max_length=10),
        ),
    ]
